version: '3'
services:
  postgres:
    image: postgres:10
    shm_size: 1024M
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 5oasd231aAS1asasx

  web:
    build: .
    links:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    command: puma

volumes:
  postgres: